services:
  - type: web
    name: healthreach-api
    env: docker
    plan: free
    branch: master
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://healthreach-apiv2.onrender.com
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /run/secrets/firebase-service-account.json

    secretFiles:
      - name: firebase-service-account.json
        mountPath: /run/secrets/firebase-service-account.json
